# Generated by Django 3.0.2 on 2020-01-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(verbose_name='Идентификатор оборудования')),
                ('name', models.CharField(max_length=50, verbose_name=' Наименование оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО Пациента')),
                ('date', models.CharField(max_length=50, verbose_name='Дата')),
                ('description', models.CharField(max_length=100, verbose_name='Название процедуры')),
                ('conclusion', models.TextField(max_length=500, verbose_name='Заключение врача')),
                ('file', models.TextField(blank=True, verbose_name='Файл')),
                ('file_md5', models.CharField(blank=True, max_length=60, verbose_name='Хеш')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='examination.Device', verbose_name='Данные диагностич оборудования')),
            ],
            options={
                'verbose_name': 'Диагностика',
                'verbose_name_plural': 'Диагностика',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(verbose_name='Частота сердцебиения')),
                ('bp_syst', models.IntegerField(verbose_name='Систолическое давление')),
                ('bp_diast', models.IntegerField(verbose_name='Диастолическое давление')),
                ('diagnostics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examination.Diagnostics')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
